DROP TRIGGER ROUTES_TRIGGER;

DROP SEQUENCE ROUTES_SEQ ;

DROP TRIGGER DESTINATIONS_TRIGGER;

DROP SEQUENCE DESTINATIONS_SEQ ;

DROP TRIGGER PLACES_TRIGGER;

DROP SEQUENCE PLACES_SEQ ;

DROP TRIGGER APPLICATIONS_TRIGGER;

DROP SEQUENCE APPLICATIONS_SEQ ;

DROP TRIGGER SPEED_CAMERAS_TRIGGER;

DROP SEQUENCE SPEED_CAMERAS_SEQ ;

DROP TRIGGER TRAFFIC_EVENTS_TRIGGER;

DROP SEQUENCE TRAFFIC_EVENTS_SEQ ;

DROP TRIGGER VEHICLE_METRICS_TRIGGER;

DROP SEQUENCE VEHICLE_METRICS_SEQ ;

DROP TRIGGER VEHICLES_TRIGGER;

DROP SEQUENCE VEHICLES_SEQ ;

DROP TRIGGER DEVICES_TRIGGER;

DROP SEQUENCE DEVICES_SEQ ;

DROP TRIGGER PLATFORMS_TRIGGER;

DROP SEQUENCE PLATFORMS_SEQ ;

DROP TRIGGER CONTACTS_TRIGGER;

DROP SEQUENCE CONTACTS_SEQ ;

DROP TRIGGER ACCOUNTS_TRIGGER;

DROP SEQUENCE ACCOUNTS_SEQ ;

DROP TRIGGER RESOURCES_TRIGGER;

DROP SEQUENCE RESOURCES_SEQ ;

---------------------------------------------------------------------------------------


DROP TABLE USER_CREDENTIALS;

DROP TABLE USER_TEAMS;

DROP TABLE USER_ROLES;

DROP TABLE USERS;

DROP TABLE ROLE_PERMISSIONS;

 DROP TABLE PERMISSIONS;

DROP TABLE MARKETING_LIST;
 
DROP TABLE LEADS;

DROP TABLE INVOICE_ROWS;

DROP TABLE INVOICES;

 DROP TABLE QUOTES;
 
DROP TABLE OPPORTUNITIES;
   
DROP TABLE MARKETING_CAMPAIGN_RULES;
  
DROP TABLE MARKETING_CAMPAIGNS;
  
DROP TABLE MARKETING_RULES;
   
DROP TABLE CASE_ENTITLEMENTS;
 
  DROP TABLE CONTRACT_CONTACTS;
  
  DROP TABLE CONTRACTS;
   
DROP TABLE CASE_MILESTONES;
  
DROP TABLE CASE_HISTORY;
  
DROP TABLE CASES;
 
DROP TABLE CASE_SOLUTIONS;

 DROP TABLE ROUTES;

 DROP TABLE DESTINATIONS;
  
 DROP TABLE PLACE_FEATURES;
 
 DROP TABLE PLACES;
  
 DROP TABLE PLACE_TYPES;
  
 DROP TABLE DESTINATION_TYPES;
  
 DROP TABLE APPLICATION_FEATURES;
 
 DROP TABLE APPLICATION_SETTINGS;
  
 DROP TABLE APPLICATION_TASKS;
 
 DROP TABLE DRIVER_RESOURCES;
 
 DROP TABLE APPLICATIONS;
  
 DROP TABLE APPLICATION_TYPES;

 DROP TABLE DRIVING_PROFILES;
 
  DROP TABLE SPEED_CAMERAS;

  DROP TABLE TRAFFIC_EVENTS;

 DROP TABLE VEHICLE_METRICS	;
 
 DROP TABLE VEHICLE_DRIVERS;
  
 DROP TABLE VEHICLE_DEVICES;
  
 DROP TABLE VEHICLE_ACCOUNTS;
 
 DROP TABLE VEHICLE_FEATURES;
 
 DROP TABLE VEHICLES;
  
 DROP TABLE VEHICLE_TYPES;
   
   DROP TABLE VEHICLE_BRANDS;
   
   DROP TABLE VEHICLE_CATEGORIES;
   
 DROP TABLE DRIVER_DEVICES;
  
 DROP TABLE INSTALLED_PACKAGES;
  
 DROP TABLE UPDATE_TARGETS;
  
 DROP TABLE UPDATE_CAMPAIGNS;
  
 DROP TABLE DEVICE_FEATURES;
  
 DROP TABLE FEATURE_TYPES;
  
 DROP TABLE DEVICES;
  
 DROP TABLE CAN_PARAMETERS	;	 
   
 DROP TABLE CAN_MESSAGES;		  
  
 DROP TABLE CAN_MATRICES;
   
 DROP TABLE DEVICE_TYPES;		
  
 DROP TABLE PACKAGE_DELTAS;
  
 DROP TABLE PACKAGES;		
   
 DROP TABLE PLATFORMS	;	 
   
 DROP TABLE ADDRESSES ;
 
 DROP TABLE ADDRESS_TYPES;
  
 DROP TABLE PHONES  ;
   
 DROP TABLE PHONE_TYPES;
   
 DROP TABLE LINKS;
   
 DROP TABLE LINK_TYPES;
   
  DROP TABLE DRIVERS;
   
 DROP TABLE DRIVING_LICENSE_TYPES;
   
 DROP TABLE RELATED_CONTACTS;
  
 DROP TABLE CONTACT_RELATIONSHIPS;
  
 DROP TABLE ACCOUNT_CONTACTS;
  
  DROP TABLE CONTACTS;
  
 DROP TABLE ROLES;
  
 DROP TABLE LANGUAGE_CODES;
  
 DROP TABLE GENDER_CODES;
	
DROP TABLE SALUTATION_CODES;
   
  DROP TABLE ACCOUNTS;
  
 DROP TABLE ACCOUNT_TYPES;
 
DROP TABLE OPERATORS;
  
  DROP TABLE RESOURCES;
	
DROP TABLE DB_SOURCES;
  
 DROP TABLE REGIONS;
  
 DROP TABLE COUNTRY_CODES;

